import SCons
import os

# prepare the Install function with possible permission override
# copied from: https://bitbucket.org/scons/scons/wiki/InstallTargets
from SCons.Script.SConscript import SConsEnvironment
SConsEnvironment.Chmod = SCons.Action.ActionFactory(os.chmod,
        lambda dest, mode: 'Chmod("%s", 0%o)' % (dest, mode))

def InstallPerm(env, dest, files, perm = 0644):
    obj = env.Install(dest, files)
    for i in obj:
        env.AddPostAction(i, env.Chmod(str(i), perm))
    return dest

# put this function "in" scons
SConsEnvironment.InstallPerm = InstallPerm

# libmosaic build script
Import ('env')

# the cursmos libraries
cursmos = env.SharedLibrary ('libcursmos', 'cursmos.c')
stream_io = env.SharedLibrary ('libcursmos_stream_io', 'cursmos_stream_io.c')

Default ([cursmos, stream_io])

## INSTALL STUFF ##
# includes -> *.h
includes = Glob ('#include/*.h')

# pkg-config files -> *.pc
pkgconfigs = Glob ('#pkgconfigs/*.pc')

env.InstallPerm ('/usr/lib', [cursmos, stream_io])
env.InstallPerm ('/usr/include/mosaic', includes)
env.InstallPerm ('/usr/share/pkgconfig', pkgconfigs)
# targets: install{,-bin,-lib,-include}
env.Alias ('install-lib', '/usr/lib')
env.Alias ('install-include', '/usr/include')
env.Alias ('install-pkgconfig', '/usr/share/pkgconfig')
env.Alias ('install', ['install-lib', 'install-include', 'install-pkgconfig'])
